### ISSUE TITLE
specfp2017 521用例死循环

### ISSUE THREAD

**Issue by hongwuya** [OpenXiangShan/CPU2017LiteWrapper#1]
specfp2017 521用例在切片过程中陷入死循环，排查与getrandom函数阻塞相关，请问这个问题如何解决？

**Comment by xyyy1420** [comment]
getrandom函数会读取熵设备获取随机数，请运行前首先确认内核启用了random和urandom设备，在启用random和urandom设备之后有一些可能可行的方案解决这个问题：
- 在关闭中断前预留几十秒时间，然后执行`cat /dev/random | head -x 16 | hexdump`检查是否能够正常输出随机数
- 改为使用 urandom 设备 `mv /dev/random /dev/chaos; ln -s /dev/urandom /dev/random`，同样需要先检查能否输出，好处是避免random在关中断之后再次出现搜集不到随机种子的问题
- 在设备树中增加预设的随机种子，同样需要先检查能否输出
```
chosen {
	rng-seed = <0xf60a3479 0x26459dee 0x315d0dcf 0xbffa313a 0x60d5699e 0x209c2ad0 0xe4946f9b 0xcca1f665>;
};

```

**Comment by hongwuya** [comment]
非常感谢您的回复，但是一些问题需要继续请教。
1 riscv-linux 是怎么启用random和urandom设备,具体需要做哪些配置和操作？
2 设备树中增加随机种子 是具体在哪个文件中增加的？

**Comment by xyyy1420** [comment]
这两个问题请参考搜索引擎或者LLM

**Comment by hongwuya** [comment]
我使用的内核是 https://github.com/OpenXiangShan/riscv-linux nanshan 分支的版本
编译配置采用了 make ARCH=riscv CROSS_COMPILE=riscv64-unknown-linux-gnu- fpga_defconfig，并且修改initramfs的source为initramfs-spec.txt
在.config文件中，可能与random相关的选项的配置如下：

CONFIG_HW_RANDOM=y
CONFIG_HW_RANDOM_TIMERIOMEM=y
...
CONFIG_WARN_ALL_UNSEEDED_RANDOM is not set
...
#
# Random Number Generation
#
# CONFIG_CRYPTO_ANSI_CPRNG is not set
CONFIG_CRYPTO_DRBG_MENU=m
CONFIG_CRYPTO_DRBG_HMAC=y
# CONFIG_CRYPTO_DRBG_HASH is not set
CONFIG_CRYPTO_DRBG=m
CONFIG_CRYPTO_JITTERENTROPY=m
CONFIG_CRYPTO_USER_API=y
CONFIG_CRYPTO_USER_API_HASH=y
# CONFIG_CRYPTO_USER_API_SKCIPHER is not set
# CONFIG_CRYPTO_USER_API_RNG is not set
# CONFIG_CRYPTO_USER_API_AEAD is not set
CONFIG_CRYPTO_HW=y
# CONFIG_CRYPTO_DEV_CCREE is not set
# CONFIG_ASYMMETRIC_KEY_TYPE is not set
...

切片生成的out文件中，与random相关的只有一行输出
[    0.010000] random: get_random_u32 called from bucket_table_alloc+0x6c/0x1e8 with crng_init=0
这是否意味着没有random设备没有启用成功？
如果没有成功，还需要做哪些操作？

**Comment by hongwuya** [comment]
> getrandom函数会读取熵设备获取随机数，请运行前首先确认内核启用了random和urandom设备，在启用random和urandom设备之后有一些可能可行的方案解决这个问题：
> 
> * 在关闭中断前预留几十秒时间，然后执行`cat /dev/random | head -x 16 | hexdump`检查是否能够正常输出随机数
> * 改为使用 urandom 设备 `mv /dev/random /dev/chaos; ln -s /dev/urandom /dev/random`，同样需要先检查能否输出，好处是避免random在关中断之后再次出现搜集不到随机种子的问题
> * 在设备树中增加预设的随机种子，同样需要先检查能否输出
> 
> ```
> chosen {
> 	rng-seed = <0xf60a3479 0x26459dee 0x315d0dcf 0xbffa313a 0x60d5699e 0x209c2ad0 0xe4946f9b 0xcca1f665>;
> };
> ```

你好，我尝试执行了 
mv /dev/random /dev/chaos; 
ln -s /dev/urandom /dev/random ;
cat /dev/random | head -x 16 | hexdump 
是有随机数输出的，但是死循环的问题并没有解决
日志中和random 相关的打印只有
[    0.010000] random: get_random_u32 called from bucket_table_alloc+0x6c/0x1e8 with crng_init=0
是否意味着random没有初始化成功？

**Comment by xyyy1420** [comment]
https://github.com/OpenXiangShan/nemu_board/pull/1 可以参考这个内核配置文件
